on:
  workflow_dispatch:  # 手動実行用

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and filter PRs
        env:
          DEV_OPS_TOKEN: ${{ secrets.DEV_OPS_TOKEN }}
          OWNER_NAME: kenta872
          REPO_NAME: dev-ops-tools
          TARGET_LABEL: bug
        run: |
          # GitHub APIからPRを取得
          echo "Fetching Pull Requests..."
          curl -H "Authorization: token $DEV_OPS_TOKEN" \
               https://api.github.com/repos/$OWNER_NAME/$REPO_NAME/pulls \
          | jq '.' > all_prs.json || { echo "Failed to fetch PRs"; exit 1; }
          
          echo "All PRs fetched. Outputting to console:"
          cat all_prs.json
          
          # 環境変数で指定されたラベルのPRをフィルタリング
          echo "Filtering PRs with label '${TARGET_LABEL}'..."
          jq "[.[] | select(.labels and (.labels | any(.name == \"$TARGET_LABEL\")))] | .[].url" all_prs.json > target_label_prs_urls.json || { echo "Error filtering PRs"; exit 2; }
          
          echo "PRs with label '${TARGET_LABEL}' URLs:"
          cat target_label_prs_urls.json
          
          # ラベルに一致するPRがない場合は終了
          if [ ! -s target_label_prs_urls.json ]; then
            echo "ラベルが'${TARGET_LABEL}'のPRはありません。"
            exit 0
          fi
          
          # URLごとに詳細情報を取得して`mergeable`がtrueのものをフィルタリング
          echo "Checking 'mergeable' status for PRs..."
          > mergeable_prs_urls.json
          while read -r pr_url; do
            pr_details=$(curl -s -H "Authorization: token $DEV_OPS_TOKEN" "$pr_url")
            mergeable=$(echo "$pr_details" | jq '.mergeable // empty')
            if [ "$mergeable" == "true" ]; then
              echo "$pr_url" >> mergeable_prs_urls.json
            fi
          done < target_label_prs_urls.json
          
          echo "Mergeable PRs URLs:"
          cat mergeable_prs_urls.json
          
          # マージ可能なPRがない場合
          if [ ! -s mergeable_prs_urls.json ]; then
            echo "マージ可能なPRはありません。"
          else
            echo "マージ可能なPRのリンク一覧:"
            cat mergeable_prs_urls.json
          fi
