on:
  workflow_dispatch:  # 手動実行用

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API
        env:
          DEV_OPS_TOKEN: ${{ secrets.DEV_OPS_TOKEN }}
        run: |
          # GitHub APIからPRを取得
          echo "Fetching Pull Requests..."
          curl -H "Authorization: token $DEV_OPS_TOKEN" \
               https://api.github.com/repos/kenta872/dev-ops-tools/pulls \
          | jq '.' > all_prs.json
          
          echo "All PRs fetched. Outputting to console:"
          cat all_prs.json
          
          # ラベルが"bug"のPRをフィルタリング
          echo "Filtering PRs with label 'bug'..."
          jq '[.[] | select(.labels | any(.name == "bug"))] | .[].html_url' all_prs.json > bug_prs_urls.json
          
          echo "PRs with label 'bug' output:"
          cat bug_prs_urls.json
          
          # 該当するPRがある場合はリンクを出力
          if [ -s bug_prs_urls.json ]; then
            echo "ラベルが'bug'のPRのリンク一覧:"
            cat bug_prs_urls.json
          else
            echo "ラベルが'bug'のPRはありません。"
          fi
